version: '3.3'

networks:
  spush-net:
    external: true

services:

  mysql:
    image: mysql:5.6
    hostname: mysql
    networks:
      - spush-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
    volumes:
       - $DATA_PATH/mysql/data:/var/lib/mysql:rw
       - $DATA_PATH/mysql/conf:/etc/mysql/conf.d:rw
       - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == centos73-245]
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

